"""empty message

Revision ID: f0d844b6c48d
Revises: a3362bb8b56e
Create Date: 2020-04-06 19:20:25.705822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d844b6c48d'
down_revision = 'a3362bb8b56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos4', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('todos4', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos4', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos4', type_='foreignkey')
    op.drop_column('todos4', 'list_id')
    op.drop_column('todos4', 'completed')
    # ### end Alembic commands ###
